import type { RouteRecordRaw } from 'vue-router'

export const routes: RouteRecordRaw[] = [
  {
    path: '/login',
    name: 'login',
    component: () => import('../views/LoginView.vue'),
  },
  {
    path: '/inscripcion/:tenantSlug/:year',
    name: 'public-admission',
    component: () => import('../views/PublicAdmissionView.vue'),
  },
  {
    path: '/estudiante/:studentId',
    name: 'student-portal',
    component: () => import('../views/StudentPortalView.vue'),
  },
  {
    path: '/',
    component: () => import('../layouts/AppLayout.vue'),
    children: [
      { path: '', name: 'dashboard', component: () => import('../views/DashboardView.vue') },
      { path: 'students', name: 'students', component: () => import('../views/StudentsView.vue') },
      { path: 'admissions', name: 'admissions', component: () => import('../views/AdmissionsView.vue') },
      { path: 'enrollments', name: 'enrollments', component: () => import('../views/EnrollmentsView.vue') },
      { path: 'enrollment-forms', name: 'enrollment-forms', component: () => import('../views/EnrollmentFormsView.vue') },
      { path: 'guardians', name: 'guardians', component: () => import('../views/CrudPlaceholderView.vue'), props: { title: 'Acudientes' } },
      { path: 'teachers', name: 'teachers', component: () => import('../views/TeachersView.vue') },
      { path: 'teacher-assignments', name: 'teacher-assignments', component: () => import('../views/TeacherAssignmentsView.vue') },
      { path: 'teacher-responsibilities', name: 'teacher-responsibilities', component: () => import('../views/TeacherResponsibilitiesView.vue') },
      { path: 'grades-groups', redirect: '/courses' },
      { path: 'academic-years', name: 'academic-years', component: () => import('../views/AcademicYearsView.vue') },
      { path: 'academic-periods', name: 'academic-periods', component: () => import('../views/AcademicPeriodsView.vue') },
      { path: 'academic-grades', name: 'academic-grades', component: () => import('../views/AcademicGradesView.vue') },
      { path: 'academic-levels', name: 'academic-levels', component: () => import('../views/AcademicYearLevelsView.vue') },
      { path: 'courses', name: 'courses', component: () => import('../views/CoursesView.vue') },
      { path: 'schedules', name: 'schedules', component: () => import('../views/SchedulesView.vue') },
      { path: 'subjects', name: 'subjects', component: () => import('../views/SubjectsView.vue') },
      { path: 'academic-areas', name: 'academic-areas', component: () => import('../views/AcademicAreasView.vue') },
      { path: 'grading-scale', name: 'grading-scale', component: () => import('../views/GradingScaleView.vue') },
      { path: 'competencies', name: 'competencies', component: () => import('../views/CompetenciesView.vue') },
      { path: 'grade-subjects', name: 'grade-subjects', component: () => import('../views/CourseSubjectsView.vue') },
      { path: 'academic-plan', name: 'academic-plan', component: () => import('../views/AcademicPlanView.vue') },
      { path: 'attendance', name: 'attendance', component: () => import('../views/AttendanceView.vue') },
      { path: 'grades', name: 'grades', component: () => import('../views/GradebookView.vue') },
      { path: 'report-cards', name: 'report-cards', component: () => import('../views/ReportCardsView.vue') },
      { path: 'committees', name: 'committees', component: () => import('../views/CommitteesView.vue') },
      { path: 'coexistence', name: 'coexistence', component: () => import('../views/CoexistenceView.vue') },
      { path: 'piar', name: 'piar', component: () => import('../views/PiarView.vue') },
      { path: 'evaluation-activities', name: 'evaluation-activities', component: () => import('../views/EvaluationActivitiesView.vue') },
      { path: 'evaluation-activities/:activityId/scores', name: 'activity-scores', component: () => import('../views/ActivityGradebookView.vue') },
      { path: 'academic-observations', name: 'academic-observations', component: () => import('../views/ObservationsView.vue') },
      { path: 'support-strategies', name: 'support-strategies', component: () => import('../views/SupportStrategiesView.vue') },
      { path: 'users', name: 'users', component: () => import('../views/UsersView.vue') },
      { path: 'navigation-admin', name: 'navigation-admin', component: () => import('../views/NavigationAdminView.vue') },
      { path: 'portfolio', name: 'portfolio', component: () => import('../views/CrudPlaceholderView.vue'), props: { title: 'Cartera' } },
      { path: 'announcements', name: 'announcements', component: () => import('../views/CrudPlaceholderView.vue'), props: { title: 'Comunicados' } },
      { path: 'reports', name: 'reports', component: () => import('../views/CrudPlaceholderView.vue'), props: { title: 'Reportes' } },
    ],
  },
]
